### ISSUE TITLE
Fix spacy error when model is not downloaded

### ISSUE THREAD

**Issue by 1n5pire** [check24-scholarships/planit#22]
Problem:
```
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
```

You can fix it by running
```
python -m spacy download en_core_web_sm
```

What is the easiest way to run this once when setting up? 
- Include in requirements.txt?
- Create a setup script?
- A friendly reminder in the README?
- ...

**Comment by jakeiridion** [comment]
added it to requirements.txt
